name: Tests

on:
  push:

jobs:
  build:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    # - name: Check out code into the Go module directory
    #   uses: actions/checkout@v1

    # - name: Get dependencies
    #   run: go mod download

    - name: Test
      run: go test -v ./...

  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Test
      run: go test -v -coverprofile=coverage.out ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_UPLOAD}}
        file: ./coverage.out
